apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: litmusctl
  name: litmusctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litmusctl
  template:
    metadata:
      labels:
        app: litmusctl
    spec:
      containers:
      - image: jonsy13/litmusctl:ci
        imagePullPolicy: Always
        name: litmusctl
        command: [ sh , -c]
        args: [ "while true; do sleep 30; done;" ]